services:
  sql-server:
    user: root
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    ports:
      - "1433:1433"
    volumes:
      - ./sql-data:/var/opt/mssql
#      - ./certs/public.crt:/var/opt/mssql/security/ca-certificates/public.crt
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=S0methingS@Str0ng!
    networks:
      - s3-backup-restore
networks:
  s3-backup-restore:
