WALG_FILE_PREFIX: "/tmp/walg-backup"
SQLSERVER_BLOB_CERT_FILE: "/home/anisur/go/src/github.com/anisurrahman75/sql-server-backup-to-azurite/certs/server.crt"
SQLSERVER_BLOB_KEY_FILE:  "/home/anisur/go/src/github.com/anisurrahman75/sql-server-backup-to-azurite/certs/server.key"
SQLSERVER_BLOB_LOCK_FILE: "/tmp/wal-g.lock"
SQLSERVER_BLOB_HOSTNAME:  "backup.local"
SQLSERVER_CONNECTION_STRING: "sqlserver://SA:S0methingS@Str0ng!@localhost:1433"

WALG_UPLOAD_CONCURRENCY:   8  # how many block upload requests handle concurrently
WALG_DOWNLOAD_CONCURRENCY: 8  # how many block read requests handle concurrently 